### ISSUE TITLE
移动端长度适配方案

### ISSUE THREAD

**Issue by wscj** [wscj/blog#14]
### 前言

现今移动设备五花八门，屏幕大小也是各不相同，所以前端需要有适配主流移动设备屏幕的解决方案。本文主要就是介绍一种简单易用的解决方案——rem。由于rem不能解决高分辨率屏幕下显示一个像素线条的问题，本文还将另外加入一个辅助方案，在使用rem的前提下，配合解决显示一像素这个问题。

### rem介绍

rem是css3新增的一个长度单位，一个rem的大小与根元素html的字体`font-size`大小相等，浏览器默认的字体大小为16px，所以一个rem的默认大小也是16px。由此可见，rem是一个相对单位，其大小取决于根元素的字体大小。正因如此，只要根据设备的屏幕宽度来动态改变根元素的字体大小，并配合使用rem长度单位，就能达到自动适配不同屏幕大小的目的。

以iphone8为例，其逻辑像素为375px（这里指设备屏幕的宽度，下同），默认字体大小为16px，若一个div的宽度要刚好铺满屏幕宽度，则其宽度为：375 / 16 = 23.4375(rem)，所以css代码这么写：

```css
div {
  width: 23.4375rem;
}
```

这段代码如果放在iphone8 plus中表现怎样呢？iphone8 plus的逻辑像素为414px，默认字体大小同样是16px，那么刚好铺满屏幕的宽度为：414 / 16 = 25.875(rem)，显然前面的23.4375rem不能铺满屏幕，所以这里需要动态改变根元素的字体大小来做适配。

如何计算根元素的字体大小呢？

假设我们的设计稿以iphone8的屏幕大小为准，即750*1334，其逻辑像素就是375px，那么根元素的字体大小可以这么计算：

```js
document.querySelector('html').style.fontSize = document.documentElement.clientWidth / 375 * 16 + 'px'
```

在iphone8中，`document.documentElement.clientWidth`等于375px，所以字体为：375 / 375 * 16 = 16(px)，铺满全屏的宽度为：375 / 16 = 23.4375(rem);

在iphone8 plus中，`document.documentElement.clientWidth`等于414px，所以字体为：414 / 375 * 16 = 17.664(px)，铺满全屏的宽度为：414 / 17.664 = 23.4375(rem)，这个值与iphone8的相等了。

所以，采用rem单位并动态计算根元素的字体大小，就能适配不同大小屏幕的设备了。

实际开发中，建议在html文档一开始的地方就嵌入`js`代码来修改根元素html的字体大小，因为这样DOM在一开始渲染的时候拿的字体大小就是修改过的，如果在DOM渲染完成之后才修改字体大小，则修改字体后浏览器需要根据新的字体大小重新渲染一次。这样一来多渲染了一次，二来可能一开始会出现格式错乱，然后又马上恢复正常，体验不好。

简单点，咱们写代码的方式简单点：

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <script>
    document.querySelector('html').style.fontSize = document.documentElement.clientWidth / 375 * 16 + 'px'
  </script>
  <!-- 这里开始引入其他js和css -->
</head>
<body>
</body>
</html>
```

平时在chrome上开发，有时候会切换不同的手机型号，切换后`document.documentElement.clientWidth`的值可能发生改变，但根元素的字体大小没有重新计算，所以样式就错乱了。这种问题在真实的设备上应该是不会出现的，因为只有全屏状态，但以防万一，我们还是写个监听函数，在`document.documentElement.clientWidth`发生变化时，重新计算根元素的字体大小，这样在chrome上切换手机型号后样式也会自动调整。所以上面的代码稍微改一下：

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <script>
    var windowResizeWidth
    window.onresize = function (e) {
      // 当宽度变化时才有必要更改fontSize
      if (document.documentElement.clientWidth !== windowResizeWidth) {
        document.querySelector('html').style.fontSize = document.documentElement.clientWidth / 375 * 16 + 'px'
        windowResizeWidth = document.documentElement.clientWidth
      }
    }
    window.onresize()
  </script>
  <!-- 这里开始引入其他js和css -->
</head>
<body>
</body>
</html>
```

以上，已经解决了适配不同手机的问题。但是，直接写rem单位，需要根据设计稿计算rem的值，每个长度都要计算一次很麻烦，并且计算出来的数字可能还有很多位小数，要一个一个敲出来，好痛苦有木有？对于这个问题，网上已经有很好的解决，就是采用sass，写个sass函数，把设计稿上的数值作为参数，这个函数自动计算rem的值并返回，举个例子：

首先定义一个全局的函数：

```css
@function px2rem($px, $base-font-size: 16px) {
  @return ($px / $base-font-size / 2) * 1rem; /* 设计稿为750，逻辑像素为375，两倍关系所有除以2 */
}
```

在需要的地方使用这个函数：

```css
div {
  width: px2rem(750px);
}
```

这样，在sass编译后，`width`的值为23.4375rem。方便多了吧？只需要写入设计稿的值，不用自己计算。

这是网上的方案，我自己觉得还能再简便点：

* **不需要px单位：** 设计稿上标注的单位不论是px还是pt，或是其他的，这都不重要，我们只关心着设计稿是750的还是720的，也可以是其他的。所以在调用`px2rem`函数时，只要写入设计稿上的长度即可，不需要带单位。当然函数内的除数32也不用带px单位。
* **简化函数名：** 如上一点所说，单位并不重要，函数名的寓意自然不应该是px转rem，函数名中的px可以去掉，那函数名直接取名为rem即可，简单好写，就这样：

```css
@function rem($len, $multiple: 2, $base-font-size: 16) {
  @return ($len / $base-font-size / $multiple) * 1rem;
}
```
```css
div {
  width: rem(750);
}
```

### 一像素解决方案

一像素的解决方案网上有很多种，本文只介绍一种很实用的。就是使用伪元素显示一像素的内容，通过伸缩达到在高分辨率屏幕下依旧显示很细的效果。

最常见的是横线条，列表、表格中经常用横线条分割内容，而单独的竖线条的情况几乎没有。

为了不贴太多代码，只介绍横线条（举一反三可推理竖线条），首先需要在全局的css里为不同的媒体查询范围设定不同的伸缩比例，为方便起见，设置固定类名`border-t`和`border-b`：

```css
@media (-webkit-min-device-pixel-ratio:1.5), (min-device-pixel-ratio:1.5) {
  .border-horizon {
    &::before, &::after {
      transform: scaleY(0.7);
    }
  }
}

@media (-webkit-min-device-pixel-ratio:2), (min-device-pixel-ratio:2) {
  .border-horizon {
    &::before, &::after {
      transform: scaleY(0.5);
    }
  }
}

@media (-webkit-min-device-pixel-ratio:2.5), (min-device-pixel-ratio:2.5) {
  .border-horizon {
    &::before, &::after {
      transform: scaleY(0.33333334);
    }
  }
}
```

*这里是以伪元素`before`为上边框`border-top`，以伪元素`after`为下边框`border-bottom`，一个元素里伪元素只有两个，所以没法满足横、竖总共四个线条同时存在，只能根据需要显示其中两个。下文还有另外一个方案可以同时显示四个边框，还支持圆角。*

接着，为方便使用，写两段sass混合，用的时候只要传线条的颜色即可：

```css
@mixin border-t($color) {
  position: relative;
  &::before {
    display: block;
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    border-top: 1px solid $color;
    content: '';
  }
}

@mixin border-b($color) {
  position: relative;
  &::after {
    display: block;
    position: absolute;
    left: 0;
    bottom: 0;
    width: 100%;
    border-top: 1px solid $color;
    content: '';
  }
}
```

使用：

```html
<div class="border-horizon" id="test"></div>
```

```css
#test {
  height: rem(100);
  @include border-t(#eee);
  @include border-b(#eee)
}
```

上面这个例子的div拥有了上下两条很细的边框

最后介绍下同时显示上下左右四条边框，并支持圆角的方案。原理其实跟上面是一样的，同样使用伪元素并通过伸缩达到目的，不同的是宽、高同时按照分辨率比例先进行伸长，再使用transform按相同比例进行缩小。

首先也是全局添加媒体查询，取个全局类名`border-all`：

```css
@media (-webkit-min-device-pixel-ratio:1.5), (min-device-pixel-ratio:1.5) {
  .border-all {
    &::before {
      width: 142.857%;
      height: 142.857%;
      transform: scale(0.7, 0.7);
    }
  }
}

@media (-webkit-min-device-pixel-ratio:2), (min-device-pixel-ratio:2) {
  .border-all {
    &::before {
      width: 200%;
      height: 200%;
      transform: scale(0.5, 0.5);
    }
  }
}

@media (-webkit-min-device-pixel-ratio:2.5), (min-device-pixel-ratio:2.5) {
  .border-all {
    &::before {
      width: 300%;
      height: 300%;
      transform: scale(0.33333334, 0.33333334);
    }
  }
}
```

为方便使用写段sass混合：

```css
@mixin border-all($color, $radius) {
  position: relative;
  &:before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    border: 1px solid $color;
    border-radius: $radius;
    transform-origin: top left;
  }
}
```
使用：

```html
<div id="test"></div>
```

```css
#test {
  width: rem(200);
  height: rem(200);
  @include border-all(#eee, rem(10));
}
```
